### ISSUE TITLE
Change config file format

### ISSUE THREAD

**Issue by TornaxO7** [TornaxO7/vibe#39]
Toml isn't that much suitable for lists with custom types:

```toml
# You can add as many shaders as you like
[[shaders]]

# configure the audio buffer for the first shader. Currently you can only set the amount of bars
# you'd like to get in the shader
[shader.audio]
amount_bars = 60

# set the frequency range (in Hz) on which the visualizer should use.
[shaders.audio.frequency_range]
start = 50
end = 10000
```

I'd like to have something like:

```
shaders = [
    Shader {
        audio = Audio {
            amount_bars = 60,
            frequency_range {
                start = 50,
                end = 10000,
            },
        },
        Code = Wgsl("""..."""),
    },

    Shader {
        ...
    }
]
```
