### ISSUE TITLE
position on display

### ISSUE THREAD

**Issue by kr0wffee** [TornaxO7/vibe#91]
can we define the position of bars/graph on the screen?

I would like to place it on top, under the waybar.
Also I think it would be convenient for someone to place it vertically on the side of the screen as well.

**Comment by TornaxO7** [comment]
Positioning and rotating isn't supported at the moment but I like the idea. I'll look into it 👍

**Comment by TornaxO7** [comment]
Hm... now I'm a bit unsure how exactly you'd like to have it. Like: Do you mean with "position" just the four different sides or really _any_ position?

**Comment by TornaxO7** [comment]
Also: How would you like to be able to set the position from a user perspective?

Would you like to be able to set a coordinate within your monitor and a rotation like
```toml
# Convention: [0, 0] is the top left corner of the monitor
position = [0, 0]
width = 1920
# Convention: Rotation is set in degree
rotation = 0.0
```
Which will put the graph/bars at the top and the bars are jumping to the bottom of your monitor.
But then the user would have to calculate everything on their own (width, position and rotation and stuff).

Or use predefined positions:
```
position = top/left/right/bottom
```
?
